import type { LevelConfig } from '@/game/Level';

export const chapter1Level2: LevelConfig = {
  name: '章节 1 - 关卡 2',
  platforms: [
    { id: 'left-platform', x: -4.65, y: 10.25, width: 6.1, height: 0.35 },
    { id: 'right-platform', x: 4.65, y: 10.25, width: 6.1, height: 0.35 },
  ],
  gate: { x: 6.35, y: 9.95, textureUrl: '/textures/gate_new.png', displayHeight: 2.6 },
  walkerStart: { x: -6.45, y: 10.425 },
  objects: [
    {
      id: 'bottle',
      railMinX: -1.5,
      railMaxX: 1.5,
      railY: 6.3,
      railZ: 16.0,
      initialT: 0.47,
      initialRotationX: 0,
      initialRotationY: 0,
      initialRotationZ: 0.6108,
      initialYOffset: 1.36,
      wrapperExtraRotation: { y: Math.PI / 2, z: -Math.PI / 2 },
      moveLimit: { up: 8, down: 8, left: 5, right: 5 },
      modelUrl: '/models/1_2.glb',
      modelScale: 0.59,
      projectionScale: 1.97,
      useGlbProjection: true,
    },
  ],
  shadowDirection: { x: 0, y: 2.9, z: -20 },
  lockWalkerUntilBridge: true,
  tutorialRotateSteps: 4,
  hintArea: { x: 0, y: 10.35, width: 3.25, height: 1.05 },
  hintText: '旋转吧，让影子跨越那道空隙',
  hintTextEn: 'Turn it — let the shadow bridge the gap',
  walkerSheet: {
    url: '/textures/baby_sheet.png',
    frameCount: 4,
    frameW: 256,
    frameH: 192,
    height: 1.067,
    yOffset: 0.015,
    indicatorXOffset: 0.4,
  },
};
