import type { LevelConfig } from '@/game/Level';
import { a } from '@/utils/asset';

export const chapter2Level2: LevelConfig = {
  name: '章节 2 - 关卡 2',
  platforms: [
    { id: 'left-platform',   x: -6.45, y:  8,     width: 2.5, height: 0.35 },
    { id: 'middle-platform', x:  0,    y:  9.125, width: 3.5, height: 0.35 },
    { id: 'right-platform',  x:  6.45, y: 10.25,  width: 2.5, height: 0.35 },
  ],
  gate: { x: 6.35, y: 9.95, textureUrl: a('/textures/gate_new.png'), displayHeight: 3.12 },
  walkerStart: { x: -6.45, y: 8.175 },
  objects: [
    {
      // 左侧物体：负责间隙 1（左↔中）
      id: 'obj-left',
      railMinX: -5.0,
      railMaxX: -2.0,
      railY: 6.3,
      railZ: 10.0,
      initialT: 0.5,
      initialRotationX: 0.07,
      initialRotationY: 1.4,
      initialRotationZ: 0,
      initialYOffset: 0.93,
      wrapperExtraRotation: { y: Math.PI / 2, z: -Math.PI / 2 },
      moveLimit: { up: 12, down: 8, left: 5, right: 5 },
      modelUrl: a('/models/4_2_2.glb'),
      modelScale: 0.34,
      projectionScale: 1.3,
      useGlbProjection: true,
      shadowXScale: 3,
      shadowYScale: 2,
    },
    {
      // 右侧物体：负责间隙 2（中↔右）
      id: 'obj-right',
      railMinX: 2.0,
      railMaxX: 5.0,
      railY: 6.3,
      railZ: 10.0,
      initialT: 0.5,
      initialRotationX: 0.07,
      initialRotationY: 1.4,
      initialRotationZ: 0,
      initialYOffset: 0.93,
      wrapperExtraRotation: { y: Math.PI / 2, z: -Math.PI / 2 },
      moveLimit: { up: 12, down: 8, left: 5, right: 5 },
      modelUrl: a('/models/4_2_2.glb'),
      modelScale: 0.34,
      projectionScale: 1.3,
      useGlbProjection: true,
      shadowXScale: 3,
      shadowYScale: 2,
    },
  ],
  shadowDirection: { x: 0, y: -0.6, z: -20 },
  bridgeTolerance: 0.2,
  lockWalkerUntilBridge: true,
  noGuide: true,
  multiBridge: true,
  hintArea: { x: 0, y: 8.85, width: 3.25, height: 1.05 },
  hintText: '点选不同的物件，寻找你的光路',
  hintTextEn: 'Click objects to switch — find your path of light',
  transitHintText: '',
  transitHintTextEn: '',
  persistentHint: true,
  walkerSheet: {
    url: a('/textures/boy_sheet.png'),
    frameCount: 5,
    frameW: 800,
    frameH: 1600,
    height: 1.8,
    yOffset: 0.0,
  },
};
