import type { LevelConfig } from '@/game/Level';

export const tutorial3: LevelConfig = {
  name: '章节 1 - 关卡 1',
  platforms: [
    { id: 'left-platform', x: -4.65, y: 10.25, width: 6.1, height: 0.35 },
    { id: 'right-platform', x: 4.65, y: 10.25, width: 6.1, height: 0.35 },
  ],
  gate: { x: 6.35, y: 9.95, textureUrl: '/textures/gate_new.png', displayHeight: 2.6 },
  walkerStart: { x: -6.45, y: 10.425 },
  objects: [
    {
      id: 'tutorial-block',
      railMinX: -3.0,
      railMaxX: 3.0,
      railY: 6.3,
      railZ: 16.0,
      initialT: 0.5,
      initialRotationX: -2.85,
      initialRotationY: 1.6,
      initialRotationZ: -0.06,
      initialYOffset: 0.75,
      wrapperExtraRotation: { y: Math.PI / 2, z: -Math.PI / 2 },
      moveLimit: { up: 8, down: 8, left: 0, right: 0 },
      modelUrl: '/models/1_1_trapezoid.glb',
      modelScale: 0.65,
      projectionScale: 2.49,
      useGlbProjection: true,
      shadowYScale: 5,
    },
  ],
  shadowDirection: { x: 0, y: -2.25, z: -20 },
  hideRotationPanel: true,
  tutorialUpSteps: 2,
  lockWalkerUntilBridge: true,
  bridgeHintText: '光路已铺就，点选人物前行',
  bridgeHintTextEn: 'The light-path is set. Click a character to walk',
  walkerSelectedHintText: '点选门扉，引导角色前往终点',
  walkerSelectedHintTextEn: 'Click the gate — guide them to the end',
  hintArea: { x: 0, y: 10.35, width: 3.25, height: 1.05 },
  hintText: '向上移动，让影子铺出第一道光路',
  hintTextEn: 'Lift upward, and let shadows lay the first beam of light',
  walkerSheet: {
    url: '/textures/baby_sheet.png',
    frameCount: 4,
    frameW: 256,
    frameH: 192,
    height: 1.067,
    yOffset: 0.015,
    indicatorXOffset: 0.4,
  },
};
